server {
    listen 80;
    client_max_body_size 10M;

    location /admin/ {
        client_max_body_size 20M;
        proxy_set_header Host $http_host;
        proxy_pass http://foodgram-back:8000/admin/;
    }

    location /s/ {
        proxy_set_header Host $http_host;
        proxy_pass http://foodgram-back:8000/s/;
    }

    location /media/ {
        alias /media/;
    }

    location /static/js/ {
        alias /static/static/js/;
    }

    location /static/css/ {
        alias /static/static/css/;
    }

    location /static/media/ {
        alias /static/static/media/;
    }

    location /static/ {
        alias /static/;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://foodgram-back:8000/api/;
    }

    location /api/docs/ {
        alias /usr/share/nginx/html/api/docs/;
        index redoc.html;
    }

    location / {
        root /static;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}