# Generated by Django 6.1.1 on 2026-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('мл', 'миллилитр'), ('л', 'литр'), ('ч. л.', 'чайная ложка'), ('ст. л.', 'столовая ложка'), ('стакан', 'стакан'), ('шт.', 'штука')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
